export const AUTH_LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'auth/LOGIN_FAILURE';

export const AUTH_LOGOUT_REQUEST = 'auth/LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'auth/LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'auth/LOGOUT_FAILURE';

export const ADVERTS_LOADED_REQUEST = 'adverts/LOADED_REQUEST';
export const ADVERTS_LOADED_SUCCESS = 'adverts/LOADED_SUCCESS';
export const ADVERTS_LOADED_FAILURE = 'adverts/LOADED_FAILURE';

export const ADVERTS_CREATED_REQUEST = 'adverts/CREATED_REQUEST';
export const ADVERTS_CREATED_SUCCESS = 'adverts/CREATED_SUCCESS';
export const ADVERTS_CREATED_FAILURE = 'adverts/CREATED_FAILURE';

export const ADVERTS_DELETED_REQUEST = 'adverts/DELETED_REQUEST';
export const ADVERTS_DELETED_SUCCESS = 'adverts/DELETED_SUCCESS';
export const ADVERTS_DELETED_FAILURE = 'adverts/DELETED_FAILURE ';

export const TAGS_LOADED_REQUEST = 'tags/LOADED_REQUEST';
export const TAGS_LOADED_SUCCESS = 'tags/LOADED_SUCCESS';
export const TAGS_LOADED_FAILURE = 'tags/LOADED_FAILURE';

export const ADVERT_LOADED_REQUEST = 'advert/LOADED_REQUEST';
export const ADVERT_LOADED_SUCCESS = 'advert/LOADED_SUCCESS';
export const ADVERT_LOADED_FAILURE = 'advert/LOADED_FAILURE ';
